# Generated by Django 4.2.1 on 2024-01-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('head1', models.CharField(max_length=50)),
                ('chead1', models.CharField(max_length=500)),
                ('head2', models.CharField(max_length=50)),
                ('chead2', models.CharField(max_length=500)),
                ('head3', models.CharField(max_length=50)),
                ('chead3', models.CharField(max_length=500)),
                ('publish_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='Blog/images')),
            ],
        ),
    ]
