# Generated by Django 4.2.1 on 2024-01-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='itemsjson',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
