# Generated by Django 4.2.1 on 2024-01-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_updateorder_alter_order_phone_alter_order_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
